### ISSUE TITLE
Challenge 1: Hello You!

### ISSUE THREAD

**Issue by nquinlan** [nquinlan/nick-zach#1]
Create a script that asks your name, and then interacts with it.

- [x] #2 The script asks for your name and then says `Hello <name>`
- [x] #3 The script asks for your name, says `Hello <name>`, and then tells you a word starting with your first initial.
- [x] #4 The script asks for your name, says `Hello <name>`, tells you a word starting with your first initial, then says, welcome back if your name is Zach or Nick.

Bonus Points: Make it so I don't have to worry about capitalization or extra spaces.

**Comment by nquinlan** [comment]
Good Job Zach! I'm only seven months late.
